#[derive(Debug, PartialEq, Clone)]
pub enum SerwerError {
    RequestBufferReadError,
    InvalidRequestLine,
    InvalidMethod,
    PathShouldStartWithSlash,
    InvalidPathQueryParam,
    InvalidPathQueryParamCharacters,
    PathQueryParamDecodeError,
    PathSegmentDecodeError,
    InvalidPathSegmentCharacters,
    PathContainsDuplicateParams,
    InvalidVersion,
    InvalidRequestHeaders,
    InvalidHeader,
    InvalidHeaderCharacters,
    InvalidCookie,
    InvalidCookieCharacters,
    InvalidRequestBody,
}
