use std::string::ToString;

#[derive(Debug, PartialEq, Clone)]
pub enum StatusCode {
    Continue = 100,
    SwitchingProtocols = 101,
    Processing = 102,
    EarlyHints = 104,
    OK = 200,
    Created = 201,
    Accepted = 202,
    NonAuthoritativeInformation = 203,
    NoContent = 204,
    ResetContent = 205,
    PartialContent = 206,
    MultiStatus = 207,
    AlreadyReported = 208,
    IMUsed = 226,
    MultipleChoices = 300,
    MovedPermanently = 301,
    Found = 302,
    SeeOther = 303,
    NotModified = 304,
    UseProxy = 305,
    TemporaryRedirect = 307,
    PermanentRedirect = 308,
    BadRequest = 400,
    Unauthorized = 401,
    PaymentRequired = 402,
    Forbidden = 403,
    NotFound = 404,
    MethodNotAllowed = 405,
    NotAcceptable = 406,
    ProxyAuthenticationRequired = 407,
    RequestTimeout = 408,
    Conflict = 409,
    Gone = 410,
    LengthRequired = 411,
    PreconditionFailed = 412,
    PayloadTooLarge = 413,
    URITooLong = 414,
    UnsupportedMediaType = 415,
    RangeNotSatisfiable = 416,
    ExpectationFailed = 417,
    ImATeapot = 418,
    MisdirectedRequest = 421,
    UnprocessableEntity = 422,
    Locked = 423,
    FailedDependency = 424,
    TooEarly = 425,
    UpgradeRequired = 426,
    PreconditionRequired = 428,
    TooManyRequests = 429,
    RequestHeaderFieldsTooLarge = 431,
    UnavailableForLegalReasons = 451,
    InternalServerError = 500,
    NotImplemented = 501,
    BadGateway = 502,
    ServiceUnavailable = 503,
    GatewayTimeout = 504,
    HTTPVersionNotSupported = 505,
    VariantAlsoNegotiates = 506,
    InsufficientStorage = 507,
    LoopDetected = 508,
    NotExtended = 510,
    NetworkAuthenticationRequired = 511,
}

impl ToString for StatusCode {
    fn to_string(&self) -> String {
        match self {
            StatusCode::Continue => String::from("100 Continue"),
            StatusCode::SwitchingProtocols => String::from("101 Switching Protocols"),
            StatusCode::Processing => String::from("101 Processing"),
            StatusCode::EarlyHints => String::from("104 Early Hints"),
            StatusCode::OK => String::from("200 OK"),
            StatusCode::Created => String::from("201 Created"),
            StatusCode::Accepted => String::from("202 Accepted"),
            StatusCode::NonAuthoritativeInformation => {
                String::from("203 Non-Authoritative Information")
            }
            StatusCode::NoContent => String::from("204 No Content"),
            StatusCode::ResetContent => String::from("205 Reset Content"),
            StatusCode::PartialContent => String::from("206 Partial Content"),
            StatusCode::MultiStatus => String::from("207 Multi-Status"),
            StatusCode::AlreadyReported => String::from("208 Already Reported"),
            StatusCode::IMUsed => String::from("226 IM Used"),
            StatusCode::MultipleChoices => String::from("300 Multiple Choices"),
            StatusCode::MovedPermanently => String::from("301 Moved Permanently"),
            StatusCode::Found => String::from("302 Found"),
            StatusCode::SeeOther => String::from("303 See Other"),
            StatusCode::NotModified => String::from("304 Not Modified"),
            StatusCode::UseProxy => String::from("305 Use Proxy"),
            StatusCode::TemporaryRedirect => String::from("307 Temporary Redirect"),
            StatusCode::PermanentRedirect => String::from("308 Permanent Redirect"),
            StatusCode::BadRequest => String::from("400 Bad Request"),
            StatusCode::Unauthorized => String::from("401 Unauthorized"),
            StatusCode::PaymentRequired => String::from("402 Payment Required"),
            StatusCode::Forbidden => String::from("403 Forbidden"),
            StatusCode::NotFound => String::from("404 Not Found"),
            StatusCode::MethodNotAllowed => String::from("405 Method Not Allowed"),
            StatusCode::NotAcceptable => String::from("406 Not Acceptable"),
            StatusCode::ProxyAuthenticationRequired => {
                String::from("407 Proxy Authentication Required")
            }
            StatusCode::RequestTimeout => String::from("408 Request Timeout"),
            StatusCode::Conflict => String::from("409 Conflict"),
            StatusCode::Gone => String::from("410 Gone"),
            StatusCode::LengthRequired => String::from("411 Length Required"),
            StatusCode::PreconditionFailed => String::from("412 Precondition Failed"),
            StatusCode::PayloadTooLarge => String::from("413 Payload Too Large"),
            StatusCode::URITooLong => String::from("414 URI Too Long"),
            StatusCode::UnsupportedMediaType => String::from("415 Unsupported Media Type"),
            StatusCode::RangeNotSatisfiable => String::from("416 Range Not Satisfiable"),
            StatusCode::ExpectationFailed => String::from("417 Expectation Failed"),
            StatusCode::ImATeapot => String::from("418 I'm a teapot"),
            StatusCode::MisdirectedRequest => String::from("421 Misdirected Request"),
            StatusCode::UnprocessableEntity => String::from("422 Unprocessable Entity"),
            StatusCode::Locked => String::from("423 Locked"),
            StatusCode::FailedDependency => String::from("424 Failed Dependency"),
            StatusCode::TooEarly => String::from("425 Too Early"),
            StatusCode::UpgradeRequired => String::from("426 Upgrade Required"),
            StatusCode::PreconditionRequired => String::from("428 Precondition Required"),
            StatusCode::TooManyRequests => String::from("429 Too Many Requests"),
            StatusCode::RequestHeaderFieldsTooLarge => {
                String::from("431 Request Header Fields Too Large")
            }
            StatusCode::UnavailableForLegalReasons => {
                String::from("451 Unavailable For Legal Reasons")
            }
            StatusCode::InternalServerError => String::from("500 Internal Server Error"),
            StatusCode::NotImplemented => String::from("501 Not Implemented"),
            StatusCode::BadGateway => String::from("502 Bad Gateway"),
            StatusCode::ServiceUnavailable => String::from("503 Service Unavailable"),
            StatusCode::GatewayTimeout => String::from("504 Gateway Timeout"),
            StatusCode::HTTPVersionNotSupported => String::from("505 HTTP Version Not Supported"),
            StatusCode::VariantAlsoNegotiates => String::from("506 Variant Also Negotiates"),
            StatusCode::InsufficientStorage => String::from("507 Insufficient Storage"),
            StatusCode::LoopDetected => String::from("508 Loop Detected"),
            StatusCode::NotExtended => String::from("510 Not Extended"),
            StatusCode::NetworkAuthenticationRequired => {
                String::from("511 Network Authentication Required")
            }
        }
    }
}
