[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serwer = { path = "../../" }
sqlite = "0.32.0"
json = "0.12.4"
bcrypt = "0.15.0"
rand = "0.8.5"